controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_action_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joints:
      - right_finger_joint
    interface_name: position

gripper_action_controller:
  ros__parameters:
    default: true
    joint: right_finger_joint
